name: chacha20_poly1305
description: Implementation of ChaCha20 stream cipher and Poly1305 authenticator in Dart following RFC-8439 #crypto
version: 1.0.0
repository: https://github.com/bitanon/chacha20_poly1305

environment:
  sdk: ^2.14.0

dependencies:
  hashlib: ^1.12.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
